repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.1
    hooks:
      - id: uv-lock
      - id: uv-export
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
