defaults:
  - _self_

seed: 42
simulation: example

trainer:
  epochs: 50
  deterministic: true
  num_sanity_val_steps: 2
  log_every_n_steps: 10
  
datamodule:
  dataset: cifar10
  train_label_size: 2100
  method: centroid
  batch_size: 512
  workers: 0

communication:
  snr: 20.0
  square: true
  awareness: aware
  antennas_receiver: 4
  antennas_transmitter: 4

model:
  layers: 0
  lr: 1e-3
  lmb: 0.0

transmitter:
  model: vit_small_patch16_224
  px_cost: 1.0

receiver:
  model: vit_base_patch16_224

wandb:
  project: semantic_alignment_mimo__neural_model
  log_model: false
